/* The following code was generated by JFlex 1.6.1 */

/* --------------------------Codigo de Usuario----------------------- */
package Compiladores;

import java_cup.runtime.*;
import java.io.Reader;
      

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Compiladores/alexico.flex</tt>
 */
class AnalizadorLexico implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\55\1\51\1\0\1\55\1\54\22\0\1\55\1\64\1\50"+
    "\2\0\1\60\1\65\1\0\1\72\1\73\1\53\1\56\1\67\1\57"+
    "\1\45\1\52\1\43\11\42\1\0\1\70\1\61\1\62\1\63\2\0"+
    "\1\30\1\40\2\40\1\46\1\40\1\37\1\37\1\34\2\37\1\35"+
    "\1\36\1\27\1\37\1\32\1\37\1\33\1\37\4\37\1\44\2\37"+
    "\1\66\1\0\1\71\1\0\1\41\1\0\1\17\1\10\1\16\1\4"+
    "\1\12\1\20\1\15\1\21\1\3\1\37\1\26\1\11\1\23\1\5"+
    "\1\2\1\24\1\37\1\14\1\13\1\6\1\7\1\1\1\25\1\22"+
    "\1\31\1\37\1\74\1\47\1\75\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uff92\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\21\2\2\3\1\4\2\1\1\5\1\6"+
    "\1\7\1\5\1\10\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\1\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\2\2\1\27\23\2\1\0\1\30\1\0"+
    "\1\31\1\0\1\32\1\5\1\0\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\2\1\43\14\2"+
    "\1\44\2\2\1\45\3\2\1\30\2\0\1\46\1\0"+
    "\1\47\3\2\1\50\1\51\1\52\1\53\1\2\1\54"+
    "\11\2\1\30\2\0\3\2\1\55\3\2\1\56\1\57"+
    "\1\2\1\60\5\2\1\61\1\2\1\62\1\63\3\2"+
    "\1\64\2\2\1\65\5\2\1\66\1\2\1\67\1\70"+
    "\2\2\1\71\1\2\1\72";

  private static int [] zzUnpackAction() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\370\0\u0136\0\u0174\0\u01b2"+
    "\0\u01f0\0\u022e\0\u026c\0\u02aa\0\u02e8\0\u0326\0\u0364\0\u03a2"+
    "\0\u03e0\0\u041e\0\u045c\0\u049a\0\u04d8\0\76\0\u0516\0\u0554"+
    "\0\76\0\u0592\0\76\0\u05d0\0\76\0\76\0\76\0\u060e"+
    "\0\u064c\0\u068a\0\u06c8\0\u0706\0\u0744\0\76\0\76\0\76"+
    "\0\u0782\0\76\0\u07c0\0\76\0\u07fe\0\u083c\0\272\0\u087a"+
    "\0\u08b8\0\u08f6\0\u0934\0\u0972\0\u09b0\0\u09ee\0\u0a2c\0\u0a6a"+
    "\0\u0aa8\0\u0ae6\0\u0b24\0\u0b62\0\u0ba0\0\u0bde\0\u0c1c\0\u0c5a"+
    "\0\u0c98\0\u0cd6\0\u0d14\0\u0d52\0\u0d90\0\76\0\u0554\0\u0554"+
    "\0\u0dce\0\u0e0c\0\76\0\76\0\76\0\76\0\76\0\76"+
    "\0\76\0\76\0\u0e4a\0\u0e88\0\u0ec6\0\u0f04\0\u0f42\0\u0f80"+
    "\0\u0fbe\0\u0ffc\0\u103a\0\u1078\0\u10b6\0\u10f4\0\u1132\0\u1170"+
    "\0\272\0\u11ae\0\u11ec\0\u122a\0\u1268\0\u12a6\0\u12e4\0\u1322"+
    "\0\u1322\0\u1360\0\u0d90\0\u139e\0\272\0\u13dc\0\u141a\0\u1458"+
    "\0\272\0\272\0\272\0\272\0\u1496\0\272\0\u14d4\0\u1512"+
    "\0\u1550\0\u158e\0\u15cc\0\u160a\0\u1648\0\u1686\0\u16c4\0\u1702"+
    "\0\u1740\0\u177e\0\u17bc\0\u17fa\0\u1838\0\272\0\u1876\0\u18b4"+
    "\0\u18f2\0\272\0\272\0\u1930\0\272\0\u196e\0\u19ac\0\u19ea"+
    "\0\u1a28\0\u1a66\0\272\0\u1aa4\0\272\0\272\0\u1ae2\0\u1b20"+
    "\0\u1b5e\0\272\0\u1b9c\0\u1bda\0\272\0\u1c18\0\u1c56\0\u1c94"+
    "\0\u1cd2\0\u1d10\0\272\0\u1d4e\0\272\0\272\0\u1d8c\0\u1dca"+
    "\0\272\0\u1e08\0\272";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\4"+
    "\1\11\1\4\1\12\1\13\1\14\1\4\1\15\1\4"+
    "\1\16\4\4\1\17\1\4\1\20\2\4\1\21\1\22"+
    "\2\4\1\23\2\4\1\2\1\24\1\25\1\4\1\26"+
    "\1\4\1\27\1\30\1\31\1\32\1\33\1\34\1\31"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\1\51\1\52\1\53\1\54"+
    "\77\0\1\4\1\55\42\4\1\0\1\4\30\0\44\4"+
    "\1\0\1\4\30\0\4\4\1\56\12\4\1\57\2\4"+
    "\1\60\21\4\1\0\1\4\30\0\1\4\1\61\42\4"+
    "\1\0\1\4\30\0\6\4\1\62\35\4\1\0\1\4"+
    "\30\0\13\4\1\63\4\4\1\64\23\4\1\0\1\4"+
    "\30\0\1\4\1\65\11\4\1\66\30\4\1\0\1\4"+
    "\30\0\10\4\1\67\10\4\1\70\22\4\1\0\1\4"+
    "\30\0\5\4\1\71\36\4\1\0\1\4\30\0\11\4"+
    "\1\72\32\4\1\0\1\4\30\0\10\4\1\73\33\4"+
    "\1\0\1\4\30\0\1\4\1\74\14\4\1\75\25\4"+
    "\1\0\1\4\30\0\20\4\1\76\23\4\1\0\1\4"+
    "\30\0\11\4\1\77\32\4\1\0\1\4\30\0\13\4"+
    "\1\100\30\4\1\0\1\4\30\0\11\4\1\101\32\4"+
    "\1\0\1\4\30\0\16\4\1\102\25\4\1\0\1\4"+
    "\41\0\1\103\27\0\2\24\1\0\1\104\1\103\41\0"+
    "\1\103\7\0\1\105\17\0\2\24\1\105\1\104\1\103"+
    "\76\0\1\106\26\0\50\107\1\110\1\0\24\107\52\0"+
    "\1\111\1\112\73\0\1\31\106\0\1\113\75\0\1\114"+
    "\75\0\1\115\75\0\1\116\100\0\1\117\101\0\1\120"+
    "\77\0\1\121\77\0\1\122\1\0\2\4\1\123\41\4"+
    "\1\0\1\4\30\0\5\4\1\124\36\4\1\0\1\4"+
    "\30\0\23\4\1\125\20\4\1\0\1\4\30\0\6\4"+
    "\1\126\35\4\1\0\1\4\30\0\10\4\1\127\33\4"+
    "\1\0\1\4\30\0\6\4\1\130\35\4\1\0\1\4"+
    "\30\0\2\4\1\131\41\4\1\0\1\4\30\0\1\4"+
    "\1\132\42\4\1\0\1\4\30\0\11\4\1\133\32\4"+
    "\1\0\1\4\30\0\12\4\1\134\31\4\1\0\1\4"+
    "\30\0\5\4\1\135\36\4\1\0\1\4\30\0\13\4"+
    "\1\136\30\4\1\0\1\4\30\0\5\4\1\137\36\4"+
    "\1\0\1\4\30\0\16\4\1\140\25\4\1\0\1\4"+
    "\30\0\13\4\1\141\30\4\1\0\1\4\30\0\10\4"+
    "\1\142\33\4\1\0\1\4\30\0\2\4\1\143\41\4"+
    "\1\0\1\4\30\0\24\4\1\144\17\4\1\0\1\4"+
    "\30\0\2\4\1\145\41\4\1\0\1\4\30\0\16\4"+
    "\1\146\25\4\1\0\1\4\30\0\10\4\1\147\33\4"+
    "\1\0\1\4\71\0\2\150\3\0\1\151\6\0\2\151"+
    "\30\0\1\152\27\0\2\104\2\0\1\152\33\0\1\153"+
    "\3\0\1\153\1\0\1\153\3\0\3\153\7\0\1\153"+
    "\7\0\1\153\1\0\2\153\2\0\1\153\27\0\51\111"+
    "\1\0\24\111\76\154\1\0\3\4\1\155\40\4\1\0"+
    "\1\4\30\0\11\4\1\156\32\4\1\0\1\4\30\0"+
    "\10\4\1\157\33\4\1\0\1\4\30\0\7\4\1\160"+
    "\34\4\1\0\1\4\30\0\10\4\1\161\33\4\1\0"+
    "\1\4\30\0\11\4\1\162\32\4\1\0\1\4\30\0"+
    "\12\4\1\163\31\4\1\0\1\4\30\0\10\4\1\164"+
    "\33\4\1\0\1\4\30\0\16\4\1\165\25\4\1\0"+
    "\1\4\30\0\11\4\1\166\32\4\1\0\1\4\30\0"+
    "\11\4\1\167\32\4\1\0\1\4\30\0\2\4\1\170"+
    "\41\4\1\0\1\4\30\0\6\4\1\171\35\4\1\0"+
    "\1\4\30\0\12\4\1\172\31\4\1\0\1\4\30\0"+
    "\12\4\1\130\31\4\1\0\1\4\30\0\10\4\1\173"+
    "\33\4\1\0\1\4\30\0\27\4\1\174\14\4\1\0"+
    "\1\4\30\0\4\4\1\175\37\4\1\0\1\4\30\0"+
    "\3\4\1\176\40\4\1\0\1\4\30\0\10\4\1\177"+
    "\33\4\1\0\1\4\71\0\2\150\74\0\2\200\3\0"+
    "\1\201\6\0\2\201\16\0\53\154\1\202\22\154\1\0"+
    "\13\4\1\203\30\4\1\0\1\4\30\0\11\4\1\204"+
    "\32\4\1\0\1\4\30\0\10\4\1\205\33\4\1\0"+
    "\1\4\30\0\25\4\1\206\16\4\1\0\1\4\30\0"+
    "\4\4\1\207\37\4\1\0\1\4\30\0\4\4\1\210"+
    "\37\4\1\0\1\4\30\0\13\4\1\211\30\4\1\0"+
    "\1\4\30\0\12\4\1\212\31\4\1\0\1\4\30\0"+
    "\11\4\1\213\32\4\1\0\1\4\30\0\13\4\1\214"+
    "\30\4\1\0\1\4\30\0\5\4\1\215\36\4\1\0"+
    "\1\4\30\0\33\4\1\216\1\217\7\4\1\0\1\4"+
    "\30\0\1\4\1\220\42\4\1\0\1\4\71\0\2\200"+
    "\1\0\1\150\72\0\2\200\32\0\52\154\1\31\1\202"+
    "\22\154\1\0\17\4\1\221\24\4\1\0\1\4\30\0"+
    "\22\4\1\222\21\4\1\0\1\4\30\0\11\4\1\223"+
    "\32\4\1\0\1\4\30\0\3\4\1\224\40\4\1\0"+
    "\1\4\30\0\14\4\1\225\27\4\1\0\1\4\30\0"+
    "\4\4\1\226\37\4\1\0\1\4\30\0\13\4\1\227"+
    "\30\4\1\0\1\4\30\0\4\4\1\230\37\4\1\0"+
    "\1\4\30\0\2\4\1\231\41\4\1\0\1\4\30\0"+
    "\15\4\1\232\26\4\1\0\1\4\30\0\16\4\1\233"+
    "\25\4\1\0\1\4\30\0\11\4\1\234\32\4\1\0"+
    "\1\4\30\0\12\4\1\235\31\4\1\0\1\4\30\0"+
    "\16\4\1\236\25\4\1\0\1\4\30\0\5\4\1\237"+
    "\36\4\1\0\1\4\30\0\4\4\1\240\37\4\1\0"+
    "\1\4\30\0\15\4\1\241\26\4\1\0\1\4\30\0"+
    "\4\4\1\242\37\4\1\0\1\4\30\0\30\4\1\243"+
    "\13\4\1\0\1\4\30\0\11\4\1\244\32\4\1\0"+
    "\1\4\30\0\11\4\1\245\32\4\1\0\1\4\30\0"+
    "\11\4\1\246\32\4\1\0\1\4\30\0\5\4\1\247"+
    "\36\4\1\0\1\4\30\0\14\4\1\250\27\4\1\0"+
    "\1\4\30\0\12\4\1\251\31\4\1\0\1\4\30\0"+
    "\11\4\1\252\32\4\1\0\1\4\30\0\13\4\1\253"+
    "\30\4\1\0\1\4\27\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7750];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\23\1\1\11\2\1\1\11\1\1\1\11"+
    "\1\1\3\11\6\1\3\11\1\1\1\11\1\1\1\11"+
    "\26\1\1\0\1\1\1\0\1\11\1\0\2\1\1\0"+
    "\10\11\26\1\2\0\1\1\1\0\24\1\2\0\51\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[171];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol symbol(int type) 
    {
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol symbol(int type, Object value) 
    {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 204) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { throw new Error("Caracter ilegal <"+yytext()+">");
            }
          case 59: break;
          case 2: 
            { System.out.print(yytext()); return symbol(sym.IDENTIFICADOR, (yytext()));
            }
          case 60: break;
          case 3: 
            { System.out.print(yytext()); return symbol(sym.ENTERO, 	(yytext()));
            }
          case 61: break;
          case 4: 
            { System.out.print(yytext()); return symbol(sym.Punto,	 		(yytext()));
            }
          case 62: break;
          case 5: 
            { /* ignora el espacio */
            }
          case 63: break;
          case 6: 
            { System.out.print(yytext()); return symbol(sym.Division, 		(yytext()));
            }
          case 64: break;
          case 7: 
            { System.out.print(yytext()); return symbol(sym.Multiplicacion,          (yytext()));
            }
          case 65: break;
          case 8: 
            { System.out.print(yytext()); return symbol(sym.Suma, 			(yytext()));
            }
          case 66: break;
          case 9: 
            { System.out.print(yytext()); return symbol(sym.Resta, 			(yytext()));
            }
          case 67: break;
          case 10: 
            { System.out.print(yytext()); return symbol(sym.Mod, 			(yytext()));
            }
          case 68: break;
          case 11: 
            { System.out.print(yytext()); return symbol(sym.Menor,	 		(yytext()));
            }
          case 69: break;
          case 12: 
            { System.out.print(yytext()); return symbol(sym.Igual,	 		(yytext()));
            }
          case 70: break;
          case 13: 
            { System.out.print(yytext()); return symbol(sym.Mayor,	 		(yytext()));
            }
          case 71: break;
          case 14: 
            { System.out.print(yytext()); return symbol(sym.Negacion, 		(yytext()));
            }
          case 72: break;
          case 15: 
            { System.out.print(yytext()); return symbol(sym.CorcheteIZQ, 		(yytext()));
            }
          case 73: break;
          case 16: 
            { System.out.print(yytext()); return symbol(sym.Coma, 			(yytext()));
            }
          case 74: break;
          case 17: 
            { System.out.print(yytext()); return symbol(sym.PuntoyComa, 		(yytext()));
            }
          case 75: break;
          case 18: 
            { System.out.print(yytext()); return symbol(sym.CorcheteDER, 		(yytext()));
            }
          case 76: break;
          case 19: 
            { System.out.print(yytext()); return symbol(sym.ParentesisIzq, 	(yytext()));
            }
          case 77: break;
          case 20: 
            { System.out.print(yytext()); return symbol(sym.ParentesisDer,		(yytext()));
            }
          case 78: break;
          case 21: 
            { System.out.print(yytext()); return symbol(sym.LlavesIzq, 			(yytext()));
            }
          case 79: break;
          case 22: 
            { System.out.print(yytext()); return symbol(sym.LlavesDer, 			(yytext()));
            }
          case 80: break;
          case 23: 
            { System.out.print(yytext()); return symbol(sym.IF, 		(yytext()));
            }
          case 81: break;
          case 24: 
            { System.out.print(yytext()); return symbol(sym.DECIMAL, 	(yytext()));
            }
          case 82: break;
          case 25: 
            { System.out.print(yytext()); return symbol(sym.Or,		 		(yytext()));
            }
          case 83: break;
          case 26: 
            { System.out.print(yytext()); return symbol(sym.CADENA, 		(yytext()));
            }
          case 84: break;
          case 27: 
            { System.out.print(yytext()); return symbol(sym.MenorIgual, 		(yytext()));
            }
          case 85: break;
          case 28: 
            { System.out.print(yytext()); return symbol(sym.IgualIgual, 		(yytext()));
            }
          case 86: break;
          case 29: 
            { System.out.print(yytext()); return symbol(sym.MayorIgual, 		(yytext()));
            }
          case 87: break;
          case 30: 
            { System.out.print(yytext()); return symbol(sym.Diferente, 		(yytext()));
            }
          case 88: break;
          case 31: 
            { System.out.print(yytext()); return symbol(sym.And,		 		(yytext()));
            }
          case 89: break;
          case 32: 
            { System.out.print(yytext()); return symbol(sym.Corchetes, 		(yytext()));
            }
          case 90: break;
          case 33: 
            { System.out.print(yytext()); return symbol(sym.Parentesis, 		(yytext()));
            }
          case 91: break;
          case 34: 
            { System.out.print(yytext()); return symbol(sym.Llaves, 			(yytext()));
            }
          case 92: break;
          case 35: 
            { System.out.print(yytext()); return symbol(sym.INT, 	(yytext()));
            }
          case 93: break;
          case 36: 
            { System.out.print(yytext()); return symbol(sym.FOR, 	(yytext()));
            }
          case 94: break;
          case 37: 
            { System.out.print(yytext()); return symbol(sym.NEW, 	(yytext()));
            }
          case 95: break;
          case 38: 
            { System.out.print(yytext()); return symbol(sym.HEXADECIMAL,	(yytext()));
            }
          case 96: break;
          case 39: 
            { System.out.print(yytext()); return symbol(sym.VOID, 	(yytext()));
            }
          case 97: break;
          case 40: 
            { System.out.print(yytext()); return symbol(sym.NULL, 	(yytext()));
            }
          case 98: break;
          case 41: 
            { System.out.print(yytext()); return symbol(sym.BOOLEANO, 	(yytext()));
            }
          case 99: break;
          case 42: 
            { System.out.print(yytext()); return symbol(sym.THIS, 	(yytext()));
            }
          case 100: break;
          case 43: 
            { System.out.print(yytext()); return symbol(sym.BOOL, 	(yytext()));
            }
          case 101: break;
          case 44: 
            { System.out.print(yytext()); return symbol(sym.ELSE, 	(yytext()));
            }
          case 102: break;
          case 45: 
            { System.out.print(yytext()); return symbol(sym.BREAK, 	(yytext()));
            }
          case 103: break;
          case 46: 
            { System.out.print(yytext()); return symbol(sym.CLASS, 	(yytext()));
            }
          case 104: break;
          case 47: 
            { System.out.print(yytext()); return symbol(sym.WHILE, 	(yytext()));
            }
          case 105: break;
          case 48: 
            { System.out.print(yytext()); return symbol(sym.PRINT, 	 (yytext()));
            }
          case 106: break;
          case 49: 
            { System.out.print(yytext()); return symbol(sym.DOUBLE, 	(yytext()));
            }
          case 107: break;
          case 50: 
            { System.out.print(yytext()); return symbol(sym.STRING, 	(yytext()));
            }
          case 108: break;
          case 51: 
            { System.out.print(yytext()); return symbol(sym.RETURN, 	(yytext()));
            }
          case 109: break;
          case 52: 
            { System.out.print(yytext()); return symbol(sym.MALLOC, 	 (yytext()));
            }
          case 110: break;
          case 53: 
            { System.out.print(yytext()); return symbol(sym.EXTENDS,	(yytext()));
            }
          case 111: break;
          case 54: 
            { System.out.print(yytext()); return symbol(sym.NEWARRAY,    (yytext()));
            }
          case 112: break;
          case 55: 
            { System.out.print(yytext()); return symbol(sym.READLINE,     (yytext()));
            }
          case 113: break;
          case 56: 
            { System.out.print(yytext()); return symbol(sym.INTERFACE,(yytext()));
            }
          case 114: break;
          case 57: 
            { System.out.print(yytext()); return symbol(sym.IMPLEMENTS,(yytext()));
            }
          case 115: break;
          case 58: 
            { System.out.print(yytext()); return symbol(sym.READINTEGER,(yytext()));
            }
          case 116: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
