
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Compiladores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Or = 42;
  public static final int Corchetes = 27;
  public static final int CorcheteIZQ = 26;
  public static final int Coma = 24;
  public static final int READLINE = 50;
  public static final int Negacion = 16;
  public static final int ParentesisDer = 44;
  public static final int LlavesIzq = 7;
  public static final int ENTERO = 33;
  public static final int IgualIgual = 2;
  public static final int DOUBLE = 31;
  public static final int Diferente = 29;
  public static final int INTERFACE = 5;
  public static final int INT = 4;
  public static final int Menor = 12;
  public static final int FOR = 35;
  public static final int IDENTIFICADOR = 37;
  public static final int READINTEGER = 49;
  public static final int Mayor = 10;
  public static final int BOOL = 19;
  public static final int Punto = 47;
  public static final int CLASS = 23;
  public static final int NEWARRAY = 40;
  public static final int Division = 30;
  public static final int IF = 38;
  public static final int GETBYTE = 58;
  public static final int THIS = 55;
  public static final int CorcheteDER = 25;
  public static final int SETBYTE = 59;
  public static final int EOF = 0;
  public static final int DECIMAL = 28;
  public static final int RETURN = 52;
  public static final int LlavesDer = 6;
  public static final int And = 18;
  public static final int NEW = 17;
  public static final int error = 1;
  public static final int CADENA = 22;
  public static final int PuntoyComa = 48;
  public static final int NULL = 41;
  public static final int BREAK = 21;
  public static final int VOID = 56;
  public static final int Llaves = 8;
  public static final int ParentesisIzq = 45;
  public static final int MenorIgual = 13;
  public static final int ELSE = 32;
  public static final int WHILE = 57;
  public static final int Parentesis = 43;
  public static final int Mod = 14;
  public static final int EXTENDS = 34;
  public static final int Resta = 51;
  public static final int HEXADECIMAL = 36;
  public static final int MayorIgual = 11;
  public static final int BOOLEANO = 20;
  public static final int STRING = 53;
  public static final int MALLOC = 9;
  public static final int Multiplicacion = 15;
  public static final int Suma = 54;
  public static final int IMPLEMENTS = 3;
  public static final int Igual = 39;
  public static final int PRINT = 46;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IgualIgual",
  "IMPLEMENTS",
  "INT",
  "INTERFACE",
  "LlavesDer",
  "LlavesIzq",
  "Llaves",
  "MALLOC",
  "Mayor",
  "MayorIgual",
  "Menor",
  "MenorIgual",
  "Mod",
  "Multiplicacion",
  "Negacion",
  "NEW",
  "And",
  "BOOL",
  "BOOLEANO",
  "BREAK",
  "CADENA",
  "CLASS",
  "Coma",
  "CorcheteDER",
  "CorcheteIZQ",
  "Corchetes",
  "DECIMAL",
  "Diferente",
  "Division",
  "DOUBLE",
  "ELSE",
  "ENTERO",
  "EXTENDS",
  "FOR",
  "HEXADECIMAL",
  "IDENTIFICADOR",
  "IF",
  "Igual",
  "NEWARRAY",
  "NULL",
  "Or",
  "Parentesis",
  "ParentesisDer",
  "ParentesisIzq",
  "PRINT",
  "Punto",
  "PuntoyComa",
  "READINTEGER",
  "READLINE",
  "Resta",
  "RETURN",
  "STRING",
  "Suma",
  "THIS",
  "VOID",
  "WHILE",
  "GETBYTE",
  "SETBYTE"
  };
}

