
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class Simbolos {
  /* terminals */
  public static final int string = 8;
  public static final int parc = 7;
  public static final int para = 6;
  public static final int hexadecimal = 14;
  public static final int por = 4;
  public static final int white = 19;
  public static final int num = 17;
  public static final int menos = 3;
  public static final int bool = 9;
  public static final int numerospuntos = 11;
  public static final int div = 5;
  public static final int EOF = 0;
  public static final int signo = 18;
  public static final int error = 1;
  public static final int comentario = 16;
  public static final int reservada = 12;
  public static final int enter = 15;
  public static final int mas = 2;
  public static final int numeros = 10;
  public static final int identificador = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mas",
  "menos",
  "por",
  "div",
  "para",
  "parc",
  "string",
  "bool",
  "numeros",
  "numerospuntos",
  "reservada",
  "identificador",
  "hexadecimal",
  "enter",
  "comentario",
  "num",
  "signo",
  "white"
  };
}

